name: Trigger auto deployment for rg1 container app

# Add push trigger for automatic deployment
on:
  push:
    branches: [main]
  workflow_dispatch: # Allows manual triggering

# Add environment variables
env:
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/bpogorelc/cicd-rag-azure-docker-githubactions:${{ github.sha }}
          file: ./Dockerfile

      - name: Deploy to Azure Container Apps
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Update container app with new image and environment variables
            az containerapp update \
              --name rg1 \
              --resource-group rg1 \
              --image ghcr.io/bpogorelc/cicd-rag-azure-docker-githubactions:${{ github.sha }} \
              --set-env-vars \
                OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}" \
                SEARCH_API_KEY="${{ secrets.SEARCH_SERVICE_API_KEY }}" \
                SEARCH_SERVICE_NAME="https://demo-bogdan-search.search.windows.net" \
                SEARCH_INDEX_NAME="demo-index" \
                API_KEY="${{ secrets.API_KEY }}" \
                ENVIRONMENT="${{ secrets.ENVIRONMENT }}" \
              --cpu 2.0 \
              --memory 4.0Gi
